---
- name: scp mysql-connector-java-8.0.18.jar
  copy:
    src: ../templates/mysql-connector-java-8.0.18.jar
    dest: /usr/share/logstash/logstash-core/lib/jars
    owner: logstash
    group: logstash
    mode: u=rw,g=rw,o=r
 
- name: create config dir
  file:
    path: "/etc/logstash/conf.d/{{platform}}"
    state: directory
  tags: config

- name: copy logstash conf.d files
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
  with_items:
    - {src: ../templates/t_behalf.j2, dest: "/etc/logstash/conf.d/{{platform}}/t_behalf.conf"}
    - {src: ../templates/t_behalf_bet_record.j2, dest: "/etc/logstash/conf.d/{{platform}}/t_behalf_bet_record.conf"}
    - {src: ../templates/t_game_record.j2, dest: "/etc/logstash/conf.d/{{platform}}/t_game_record.conf"}
    - {src: ../templates/t_member.j2, dest: "/etc/logstash/conf.d/{{platform}}/t_member.conf"}
    - {src: ../templates/t_member_balance.j2, dest: "/etc/logstash/conf.d/{{platform}}/t_member_balance.conf"}
    - {src: ../templates/t_member_balance_change.j2, dest: "/etc/logstash/conf.d/{{platform}}/t_member_balance_change.conf"}
  tags: config

- name: add config to pipeline
  lineinfile:
    path: /etc/logstash/pipelines.yml
    regexp: "^-\\s+pipeline.id:\\s+{{platform}}"
    line: "- pipeline.id: {{platform}}"
  tags: config  

- name: add platform config
  lineinfile:
    path: /etc/logstash/pipelines.yml
    regexp: "/etc/logstash/conf.d/{{platform}}/*.conf"
    line: "  path.config: \"/etc/logstash/conf.d/{{platform}}/*.conf\""
    insertafter: "^-\\s+pipeline.id:\\s+{{platform}}"
  tags: config 

- name: change /etc/logstash
  file:
    dest: /etc/logstash
    owner: logstash 
    group: logstash 
    mode: u=rwX,g=rX,o=rX 
    recurse: yes
  tags: config    

- name: start logstash
  systemd:
    name: logstash
    daemon_reload: yes
    state: started
    enabled: yes
