---
- name: check java is installed
  shell: command -v java
  register: is_java_exist
  ignore_errors: yes
  
- debug: var=is_java_exist

- name: install java
  yum:
    name: java-1.8.0-openjdk
  when:  is_java_exist.failed 

- name: install logstash rpm package
  yum:
    name: https://artifacts.elastic.co/downloads/logstash/logstash-7.5.0.rpm


