---
- name: add hostname to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{hostvars[item]['ansible_ssh_host']}}"
    line: " {{hostvars[item]['ansible_ssh_host']}}    {{hostvars[item]['inventory_hostname']}}"
    state: present
  with_items: "{{groups['orch']}}"


- name: add orchestrator group
  group:
    name: orchestrator
    state: present

- name: add orchestrator user
  user:
    name: orchestrator
    group: orchestrator 
    shell: /sbin/nologin
    create_home: no 

- name: change orch priv
  file:
    dest: /usr/local/orchestrator
    owner: orchestrator
    group: orchestrator
    recurse: yes
    mode: u=rwx

- name: create config file and systemctl service file
  template:
    src:   "{{item.src}}"
    dest:  "{{item.dest}}"
    owner: "{{item.owner}}"
    group: "{{item.group}}"
  with_items:
    - {src: ../templates/temp_orch.j2, dest: /etc/orchestrator.conf.json, owner: orchestrator, group: orchestrator  }
    - {src: ../templates/temp_orch_systemctl.j2, dest: /lib/systemd/system/orchestrator.service, owner: root, group: root}

- name: start orch systemctl service
  systemd:
    name: orchestrator
    daemon_reload: yes
    state: started
    enabled: yes

