---
- name: install epel repo
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
    
- name: install elasticsearch rpm key
  rpm_key:
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
  
- name: install elasticsearch 7.x rpm repository
  yum_repository:
    name: elasticsearch
    description: Elasticsearch repository for 7.x packages
    baseurl: https://artifacts.elastic.co/packages/7.x/yum
    gpgcheck: true
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: install python-pip
  yum:
    name: python-pip
   
- name: installl python expect lib
  pip:
    name: pexpect
     
- name: install elasticsearch 7.x
  yum:
    name: "{{version}}"
    state: present
    update_cache: true

- name: set es password
  expect:
    command:  /usr/share/elasticsearch/bin/elasticsearch-keystore add bootstrap.password
    responses:
      (?i)password: "{{es_pass}}"
  when: es_role  == "master"    

- name: disable firewall
  systemd:
    name: "{{item.name}}"
    state: stopped
    enabled: no
  with_items:
   - { name: firewalld }
