---

- name: remove mariadb-libs and install mysql8.0
  yum:
    name: "{{item.name}}"
    state: "{{item.state}}"
  with_items:
    - { name: mariadb-libs, state: absent}
    - { name: epel-release, state: present}
    - { name: python-pip, state: present}
    - { name: yum-utils, state: present}
    - { name: "https://dev.mysql.com/get/mysql80-community-release-el7-3.noarch.rpm", state: present}
    - { name: "mysql-community-server-0:{{mysqlversion}}.el7.x86_64", state: present}

- name: pip install PyMySQL
  pip:
    name: PyMySQL
    

- name: Disable SELinux
  selinux:
    state: disabled

- name: set system timezone
  shell: timedatectl set-timezone Asia/Hong_Kong

