---
- name: export data
  shell: >
       mydumper \ 
         --database={{backupdbname}}  \
         --host=127.0.0.1             \
         --port={{srcdbport}}         \
         --user={{srcdbmylogin}}      \
         --password={{srcdbmypasswd}} \
         --outputdir={{backupdir}}/{{backupdbname}}    \
         --rows=50000                 \
         --threads=10                 \
         --trx-consistency-only       \
         --routines                   \
         --events                     \
         --triggers                    
                 
  args:
    chdir: "{{backupdir}}"
  register: output
  when: bk_type==1
 
- name: import data
  shell: >
      myloader                      \
      --host={{destdbhost}}         \
      --port={{destdbport}}         \
      --password={{destdbmypaasswd}} \
      --user={{destdbmylogin}} \
      --directory={{backupdir}}/{{backupdbname}} \
      --threads=10                               \
      --queries-per-transaction=50000            
  args:
    chdir: "{{backupdir}}"
  when: bk_type==1

