---
- name: mysqldump dump
  shell: >
    mysqldump -d -u{{srcdbmylogin}}  \
                 -p{{srcdbmypasswd}}  \
                 -P{{srcdbport}} \
                 --set-gtid-purged=OFF \
                 -h 127.0.0.1  {{backupdbname}} > {{backupdir}}/{{backupdbname}}/{{backupdbname}}.sql
  when: bk_type==0

- name: create db 
  mysql_db:
    name: "{{backupdbname}}"
    state: present
    login_host: "{{destdbhost}}"
    login_password: "{{destdbmypaasswd }}"
    login_port: "{{destdbport}}"
    login_user: "{{destdbmylogin}}"
  when: bk_type==0

- name: import data
  mysql_db:
    name: "{{backupdbname}}"
    state: import
    target: "{{backupdir}}/{{backupdbname}}/{{backupdbname}}.sql"
    login_host: "{{destdbhost}}"
    login_password: "{{destdbmypaasswd }}"
    login_port: "{{destdbport}}"
    login_user: "{{destdbmylogin}}"
  when: bk_type==0

- name: get table list
  shell: >
    mysql -u{{destdbmylogin}} \
          -p{{destdbmypaasswd }} \ 
          -h{{destdbhost}} \
          -P{{destdbport}} \
          -D{{backupdbname}} \
          -e "show tables;"
  register: tabs
  when: bk_type==0

- name: discard tablespace
  shell: >
    mysql -u{{destdbmylogin}} \
          -p{{destdbmypaasswd }} \
          -h{{destdbhost}} \
          -P{{destdbport}} \
          -D{{backupdbname}} \
          -e "SET FOREIGN_KEY_CHECKS=0; ALTER TABLE {{item}}  DISCARD TABLESPACE;"
  with_items: "{{tabs.stdout_lines}}"
  when: bk_type==0 and  'Tables_in' not in item


- name: get source database data file dir
  mysql_variables:
    login_host: 127.0.0.1
    login_user: "{{srcdbmylogin}}"
    login_password: "{{srcdbmypasswd}}"
    login_port: "{{srcdbport}}"
    variable: datadir
  register: source_dbpath
  when: bk_type==0

- name: get destination database data file dir
  mysql_variables:
    login_host: "{{destdbhost}}"
    login_password: "{{destdbmypaasswd }}"
    login_port: "{{destdbport}}"
    login_user: "{{destdbmylogin}}"
    variable: datadir
  register: dest_dbpath
  when: bk_type==0

- name: rsync table data
  shell:  python /tmp/mysql_cp.py {{item}} {{dest_dbpath.msg}}{{backupdbname}}
  with_items: "{{tabs.stdout_lines}}"
  when: bk_type==0 and  'Tables_in' not in item
  


  
